### ISSUE TITLE
Les valeurs "département" et "region" pour le paramètre "fields" renvoient une erreur

### ISSUE THREAD

**Issue by elkami12** [sgmap/geoapi#3]
Pourtant indiquées dans la documentation, les appels avec les valeurs "département" et "region" pour le paramètre "fields" renvoient une erreur:

Exemples:
`https://geo.api.gouv.fr/communes?fields=code,departement&nom=paris` renvoie:

```
TypeError: req.db.departements.queryByCode is not a function
   at formatOne (/srv/www/communes/lib/helpers.js:39:45)
   at res.send.result.map.commune (/srv/www/communes/server.js:59:36)
   at Array.map (native)
   at /srv/www/communes/server.js:59:21
   at Layer.handle [as handle_request] (/srv/www/communes/node_modules/express/lib/router/layer.js:95:5)
   at next (/srv/www/communes/node_modules/express/lib/router/route.js:131:13)
   at /srv/www/communes/lib/helpers.js:31:5
   at Layer.handle [as handle_request] (/srv/www/communes/node_modules/express/lib/router/layer.js:95:5)
   at next (/srv/www/communes/node_modules/express/lib/router/route.js:131:13)
   at /srv/www/communes/lib/helpers.js:13:5
```

**Comment by jdesboeufs** [comment]
Un problème de déploiement apparemment.
Identique à sgmap/api-communes#65 qui avait été corrigé.

**Comment by jdesboeufs** [comment]
Corrigé en production.
Merci !
